const GENERAL = [
	"What is the worst fashion decision you ever made?",
	"If you had to eat one meal for the rest of your life what would it be?",
	"If you could change gender for a day what’s the first thing you would do?",
	"What’s your biggest irrational phobia and why?",
	"If you became president today, what’s the first bill you would pass?",
	"If you could have any superpower what would it be?",
	"Who was your first celebrity crush?",
	"If you could be somebody else for a day who would you be?",
	"If you were a wrestler what would your entrance theme be?",
	"If aliens landed on earth today and offered to abduct you, would you go with them?",
	"If you could time travel, where is the first place you would go?",
	"If you could live in any historical period, which one would you choose?",
	"If you could be reincarnated as any animal, which one would you choose?",
	"Which famous actor would play you in the movie of your life?",
	"Which famous person, dead or alive, would like by your side during a zombie apocalypse?",
	"What is the worst date you’ve ever been on and why?",
	"What’s a common phrase used in your family that nobody else uses?",
	"What are your most commonly used emojis?",
	"If you could teleport anywhere in the world right now, where would you go?",
	"If you could appear on any game show, which one would you choose?" 
];

const ADULTS = [
	"What do you feel is the secret to a long and happy marriage?" ,
	"What are your biggest fears and biggest excitements about our relationship going forward?" ,
	"Do you feel more emotionally connected than we did early in our relationship?" ,
	"For a happy marriage, do you have to set boundaries?",
	"Is there anything that we used to do before we were married that you miss doing now?" ,
	"What were your first impressions when you met me?" ,
	"What have you learned to appreciate about me that you did not know when we were first married?",
	"Do you think infidelity is always a deal breaker, no matter what?" ,
	"If you had three wishes to wish for our future, what would they be?" ,
	"If you could change one thing about our relationship what would it be?" ,
	"What was the most embarrassing thing to happen at your bachelorette/bachelor party?" ,
	"What’s something you used to believe about relationships, but no longer do?" ,
	"Do you think we manage to balance home and work life well?" ,
	"Do you think we argue more or less than other married couples?" ,
	"What did your family think of me when we first met?",
	"If I loved a name for a child but you hated it, would you let me call our child that?",
	"What do you feel is the secret to a long and happy marriage?" ,
	"What are your biggest fears and biggest excitements about our relationship going forward?",
	"Do you have a naughty fantasy you’ve never shared with me before?",
	"Do you think social media has impacted our relationship since we’ve been married?" ,
	"Did your family or friends find the best man’s speech offensive?" ,
	"Is there anything you’ve always wondered about me, but have hesitated to ask" ,
	"What do you think is the biggest cause of or contributing factor towards divorce?" ,
	"If you could go back, would you have done anything differently about the wedding?" ,
	"If you could go back, would you have moved abroad to start our life together?",
	"What have we learned most about each other since being together?" ,
	"What was the most fun thing we did on our honeymoon?",
	"Which of our marriage vows do you think is the most important?" ,
	"What has been the best anniversary gift you’ve gotten me?" ,
	"What do you think would be the most romantic place for us to travel together?" ,
	"What has been the most romantic thing you’ve done for me?" ,
	"When we got married, how did we decide where we wanted to live?" ,
	"Looking back now, was there a situation you wished you’d handled differently?" ,
	"Do we still make time for each other now as we did at the start?" ,
	"What annoying habits do I have?" ,
	"Did anything funny happen at the wedding?" ,
	"What are some situations we’ve been through that have made us stronger as people?" ,
	"What’s one thing I do around the house that annoys you?" ,
	"What world events have had an impact on our marriage?" ,
	"When did you realize I was the one?" ,
	"Do you prefer sitting under the stars or watching a sunset?" ,
	"What helps you de-stress?" ,
	"What strengths do we both bring to the relationship?" ,
	"Do you think we’re closer now than we were at the beginning of the relationship?" ,
	"Do you think our star signs have helped us to be a closer couple?",
	"When you think of our home, what’s the first thing that comes to mind?" ,
	"What’s the best advice someone has ever given you?" ,
	"What’s your most significant achievement?" ,
	"If you could bring a previous pet back from the dead, who would you pick?" ,
	"If you could sum up our relationship in 3 words, what would it be?" ,
	"Do you think our kids are or will be more like you or more like me?" ,
	"If you could pick any other era to live in, which would you choose and why?" ,
	"Do you believe in life after death?" ,
	"What’s one thing you’ve done that other people would never know?" ,
	"What’s the best gift you’ve ever received?",
	"Do you think we will all live on a different planet one day, or can we save this one?" ,
	"Do you think humans were created or evolved from apes?" ,
	"What’s a regret you have about your life so far?",
	"What moment changed your life for good?" ,
	"If you could change one thing about yourself, what would it be and why?" ,
	"Rank your three happiest days so far?",
	"At what moment in your life so far have you felt most alive?" ,
	"Have you ever really fallen out with a close friend?" ,
	"Before you met me, were you heartbroken?",
	"Do you think there is any such thing as pure happiness? Have you ever experienced it in life?" ,
	"What’s the most trouble you’ve ever been in?" ,
	"What legacy would you like to leave in this world?" ,
	"Do you think you have a purpose in life? If so, what is it?" ,
	"What does true love look like to you?" ,
	"What do you think our love language is?" ,
	"Are you proud of me?" ,
	"How can I show you more love and affection?" ,
	"What can we do to improve our relationship?" ,
	"In what ways can we make our finances better?" ,
	"What’s going on in your head right now?" ,
	"What can you tell me that will give me insight into what you’re thinking?" ,
	"Which romantic film best relates to us?" ,
	"If someone wrote a book about our relationship, would it be a romantic comedy or emotionally profound?" ,
	"If someone gave you a letter letting you know how our relationship will look in 10 years, would you read it?" ,
	"What can I do to make you feel more secure?" ,
	"Would you like me to give you more surprises in life?" ,
	"If you could only eat one of my meals for the rest of your life, what would it be and why?" ,
	"Would you like to go on more date nights?" ,
	"Would a new challenge help us grow as people?" ,
	"Do I tell you enough about how much you mean to me?" ,
	"Which movie, no matter how many times you watch it, always makes you cry?" ,
	"Do you remember the story of how we met?" ,
	"Which couple out of your friends or family do you envy the most?" ,
	"Tell me about your first love?" ,
	"What would have been a relationship deal breaker for you when we first met?" ,
	"What can we do to be more intimate with each other?" ,
	"What would be the perfect end to a date with me?" ,
	"What’s the worst chat-up line you used when dating?" ,
	"What was the most embarrassing thing you did to get the attention of a girl/boy?" ,
	"What memory of me always sticks in your head?" ,
	"What part of my body can you not get enough of?" ,
	"Is there anything new you would like to try in bed? If so, what is it?" ,
	"Would you like us to have more foreplay?" ,
	"What could I wear that would get you in the mood?" ,
	"What always makes you happy when you’re sad?" ,
	"Before we got together, what was your type?" ,
	"What does romance mean to you?" ,
	"Have you ever been tempted to end our relationship?" ,
	"Would you tell me if you had feelings for somebody else?" ,
	"What’s the most romantic thing you’ve ever seen?" ,
	"What song always reminds me of you?" ,
	"At what age did you have the dreaded birds and the bees talk?" ,
	"What romantic getaway would you like to try next?" ,
	"Do you think we’re soulmates? Do you think soulmates exist?" ,
	"Have you ever been jealous of something I have?" ,
 	"What’s your greatest dream, and did it come true?" 

];

const bible_questions = [
	"Q1: How many commandments are there in the Bible?",
	"Q2: What is the first book in the new testament?",
	"Q3: What is the first book in the old testament?",
	"Q4: What did God do on the 7th day?",
	"Q5: Who built an ark?",
	"Q6: Who is the mother of Jesus?",
	"Q7: What are the first three words in Genesis?",
	"Q8: What is the shortest verse in the bible?",
	"Q9: What is the longest chapter in the bible?",
	"Q10: What is the middle chapter in the bible?",
	"Q11: What is the longest verse in the bible?",
	"Q12: How many sons did Jacob have?",
	"Q13: How old was Abraham when Isaac was born?",
	"Q14: How old was Sarah when Isaac was born?",
	"Q15: Who was older Ishmael or Isaac?",
	"Q16: What is the meaning of the name Isaac in the bible?",
	"Q17: Where was Jesus buried?",
	"Q18: How many days was Jesus in the tomb?",
	"Q19: What is the shortest book in the new testament?",
	"Q20: How many days was Jonah in the belly of the big fish?",
	"Q21: Who wrote the Book of Revelation?",
	"Q22: What does the word 'gospel' mean?",
	"Q23: How many disciples did Jesus have?",
	"Q24: How many times did Peter deny Jesus?",
	"Q25: What is another name for the Sermon on the Mount?",
	"Q26: Where was Moses born in the Bible?",
	"Q27: How many plagues of Egypt are there in the bible?",
	"Q28: What were the 10 plagues of Egypt?",
	"Q29: Who killed Goliath?",
	"Q30: Who threw Daniel in the lion’s den?",
	"Q31: Who threw Shadrach Meshach and Abednego in the fire?",
	"Q32: Who was the Pharisee that had a private meeting with Jesus at night?",
	"Q33: Which chapter of Hebrews tells of great heroes of faith?",
	"Q34: Which book in the Bible tells of Paul’s conversion?",
	"Q35: Prophet Isaiah lived in which city?",
	"Q36: Ahab was the king of which country?",
	"Q37: Finish this sentence: We are not saved by our own works, we are saved by _?",
	"Q38: What did David use to kill Goliath?",
	"Q39: What did the bread and wine Jesus served the disciples at the Last Supper represent?",
	"Q40: Even though he promised Jesus he would die for him, what did Peter do when Jesus was arrested?",
	"Q41: What was the name of the demon who possessed the man in the tomb?",
	"Q42: What happened to Joseph after he had refused to commit adultery with his master's wife?",
	"Q43: What is the name given to an unusual happening that goes against the laws of nature?",
	"Q44: What is the meaning of 'Epistle'?",
	"Q45: Jesus said what is the greatest display of love?",
	"Q46: Which Queen visited King Solomon because she had heard of his fame?",
	"Q47: True or False, the word 'Easter' appears in the Old Testament?",
	"Q49: Who is the man that wanted to kill baby Jesus?",
	"Q50: How many books of poetry are in the Old Testament?",
	"Q51: Ten men with what condition were healed by Jesus?",
	"Q52: In the book of Genesis, God did what to Adam and Eve when he found that they had sinned?",
	"Q53: What was the animal Satan appeared as to Eve in the book of Genesis?",
	"Q54: Which book tells of seven seals and seven trumpets?",
	"Q55: What is Pentecost?" ,
	"Q56: What is the sacrament in which we first become children of God?",
	"Q57: Who was the boy who killed the Philistine giant?",
	"Q58: What does 'Eve' mean?",
	"Q59: Why is Easter celebrated?",
	"Q60: Which prophet had to lay on his left side for six months?",
	"Q61: How old was Abraham in the bible when he died?",
	"Q62: How old was Jesus when he was crucified?",
	"Q63: What is the shortest book in the old testament?",
	"Q64: How old was Jesus when he returned from Egypt?",
	"Q65: Who married Boaz in the bible?",
	"Q66: How old was Joseph when he married Mary in the bible?",
	"Q67: Who married Rebecca in the bible?",
	"Q68: Who had the most wives in the Bible?",
	"Q69: Where did Cain's wife come from in the Bible?",
	"Q70: What was Lot's wife name in the Bible?"

	
]

const bible_answers = [
	{Question:	"Q1",	answer:	 "10"},
	{Question:	"Q2",	answer:	 "Matthew"},
	{Question:	"Q3",	answer:	 "Genesis"},
	{Question:	"Q4",	answer:	 "He rested"},
	{Question:	"Q5",	answer:	 "Noah"},
	{Question:	"Q6",	answer:	 "Mary"},
	{Question:	"Q7",	answer:	 "In the beginning"},
	{Question:	"Q8",	answer:	 "Jesus wept"},
	{Question:	"Q9",	answer:	 "Psalm 119"},
	{Question:	"Q10",	answer:	 "Psalm 117"},
	{Question:	"Q11",	answer:	 "Esther 8:9"},
	{Question:	"Q12",	answer:	 "12"},
	{Question:	"Q13",	answer:	 "100"},
	{Question:	"Q14",	answer:	 "90"},
	{Question:	"Q15",	answer:	 "Ishmael"},
	{Question:	"Q16",	answer:	 "One who laughs"},
	{Question:	"Q17",	answer:	 "In a tomb"},
	{Question:	"Q18",	answer:	 "3 days"},
	{Question:	"Q19",	answer:	 "2 John"},
	{Question:	"Q20",	answer:	 "3 days and 3 nights"},
	{Question:	"Q21",	answer:	 "Apostle John"},
	{Question:	"Q22",	answer:	 "Good News"},
	{Question:	"Q23",	answer:	 "12"},
	{Question:	"Q24",	answer:	 "3 times"},
	{Question:	"Q25",	answer:	 "The Beatitudes"},
	{Question:	"Q26",	answer:	 "Goshen in ancient Egypt"},
	{Question:	"Q27",	answer:	 "10"},
	{Question:	"Q28",	answer:	 "Water turning to blood; Frogs, Lice, Flies, Livestock pestilence, Boils, Hail, Locusts, Darkness and the Killing of firstborn children"},
	{Question:	"Q29",	answer:	 "David"},
	{Question:	"Q30",	answer:	 "King Darius"},
	{Question:	"Q31",	answer:	 "Nebuchadnezzar, King of Babylon"},
	{Question:	"Q32",	answer:	 "Nicodemus"},
	{Question:	"Q33",	answer:	 "Hebrews 11"},
	{Question:	"Q34",	answer:	 "Acts"},
	{Question:	"Q35",	answer:	 "Jerusalem"},
	{Question:	"Q36",	answer:	 "Israel"},
	{Question:	"Q37",	answer:	 "Grace"},
	{Question:	"Q38",	answer:	 "A sling and a stone"},
	{Question:	"Q39",	answer:	 "Body & Blood, Soul & Divinity of Jesus Christ"},
	{Question:	"Q40",	answer:	 "Peter denied that he knew Jesus three times"},
	{Question:	"Q41",	answer:	 "Legion"},
	{Question:	"Q42",	answer:	 "He was put in jail"},
	{Question:	"Q43",	answer:	 "Miracles"},
	{Question:	"Q44",	answer:	 "Letter"},
	{Question:	"Q45",	answer:	 "That a man would lay down his life for a friend"},
	{Question:	"Q47",	answer:	 "False"},
	{Question:	"Q48",	answer:	 "A reenactment of Mary Magdalene’s visit to Jesus’ tomb on the morning of his Resurrection"},
	{Question:	"Q49",	answer:	 "King Herod"},
	{Question:	"Q50",	answer:	 "Five"},
	{Question:	"Q51",	answer:	 "Leoprasy"},
	{Question:	"Q52",	answer:	 "He expelled them from the garden of Eden"},
	{Question:	"Q53",	answer:	 "Serpent"},
	{Question:	"Q54",	answer:	 "Revelation"},
	{Question:	"Q55",	answer:	 "When the Holy Spirit descended onto the apostles in flaming fire to give them the gifts to courageously proclaim the good news of Jesus"},
	{Question:	"Q56",	answer:	 "Baptism"},
	{Question:	"Q57",	answer:	 "David"},
	{Question:	"Q58",	answer:	 "Mother of all living"},
	{Question:	"Q59",	answer:	 "It is the day of Jesus Christ's Resurrection"},
	{Question:	"Q60",	answer:	 "Ezekiel"},
	{Question:	"Q61",	answer:	 "175 (Genesis 25:7)"},
	{Question:	"Q62",	answer:	 "No one knows as it was not recorded in the Bible"},
	{Question:	"Q63",	answer:	 "Obadiah (21 verses only)"},
	{Question:	"Q64",	answer:	 "The Bible does not say"},
	{Question:	"Q65",	answer:	 "Ruth"},
	{Question:	"Q66",	answer:	 "Not mentioned in the Bible"},
	{Question:	"Q67",	answer:	 "Isaac"},
	{Question:	"Q68",	answer:	 "King Solomon"},
	{Question:	"Q69",	answer:	 "Its not mentioned in the Bible but it is widely believed that Cain married his sister"},
	{Question:	"Q70",	answer:	 "Her name is not mentioned in the Bible"},

		

]
